CREATE TABLE names (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE traits (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    trait TEXT NOT NULL UNIQUE
);

CREATE TABLE behaviors (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    behavior TEXT NOT NULL UNIQUE
);

CREATE TABLE plots (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    content TEXT NOT NULL
);

CREATE TABLE encounters (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    content TEXT NOT NULL
);
