"""Add Character, Quest, Trait, and CharacterBehavior models

Revision ID: 760f3599f7f0
Revises: eb8f97967112
Create Date: 2024-06-23 10:43:09.753768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '760f3599f7f0'
down_revision: Union[str, None] = 'eb8f97967112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
